{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test_dict.yaml'", "trace": "self = <test_05.TestProcurementType object at 0x04754B50>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-05' % (self.lab)\n        self.ip = gl.get_value('apiip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.supplierId = self.id = ReadExtract().read_extract()['supplierId']\n\ntestcase\\test_05.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <testcase.axtr.ReadExtract object at 0x04754A30>\n\n    def read_extract(self):\n        #打开文件\n>       with open('test_dict.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'test_dict.yaml'\n\ntestcase\\axtr.py:6: FileNotFoundError"}, "start": 1615859920020, "stop": 1615859920020, "uuid": "58feaf0d-c947-4ee2-aea3-1a24f2b3b15a", "historyId": "428fd0b8d6f2944ddc88e582ce0f1e5b", "testCaseId": "37cac1bf8e4bae65dbd02efa55192738", "fullName": "testcase.test_05.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例5"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_05"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "162464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_05"}]}