{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../testcase/test_dict.yaml'", "trace": "self = <test_09.TestProcurementType object at 0x04269B30>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-09' % (self.lab)\n        self.ip = gl.get_value('apiip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.id = ReadExtract().read_extract()['id']\n\ntestcase\\test_09.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <data_test.axtr.ReadExtract object at 0x04269150>\n\n    def read_extract(self):\n        #打开文件\n>       with open('../testcase/test_dict.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../testcase/test_dict.yaml'\n\ndata_test\\axtr.py:7: FileNotFoundError"}, "start": 1616492435163, "stop": 1616492435164, "uuid": "369cb4f0-9ff8-4ff6-85dd-7af9412cf994", "historyId": "22504a71f49f935b2f04c443a7756ba4", "testCaseId": "d305972b55e75a1f0d31c05ab24aae36", "fullName": "testcase.test_09.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例9"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_09"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "133224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_09"}]}