{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../testcase/test_dict.yaml'", "trace": "self = <test_04.TestProcurementType object at 0x04269A70>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-04' % (self.lab)\n        self.ip = gl.get_value('apiip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.id = ReadExtract().read_extract()['id']\n\ntestcase\\test_04.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <data_test.axtr.ReadExtract object at 0x0432B5D0>\n\n    def read_extract(self):\n        #打开文件\n>       with open('../testcase/test_dict.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../testcase/test_dict.yaml'\n\ndata_test\\axtr.py:7: FileNotFoundError"}, "start": 1616492433707, "stop": 1616492433708, "uuid": "0aee8acd-4446-44ee-9e17-599bf2d33eec", "historyId": "09ea47c93403a114b9ba2b3628ea1a44", "testCaseId": "90b6349d51fadaf27b87d0fd9af3eb3b", "fullName": "testcase.test_04.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例4"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_04"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "133224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_04"}]}