{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data_test/send.yaml'", "trace": "self = <test_22.TestProcurementType object at 0x0432DCF0>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-22' % (self.lab)\n        self.ip = gl.get_value('AIip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.appliedSupplierIds = self.id = Con().con_read()['appliedSupplierIds']\n\ntestcase\\test_22.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <testcase.axtr.Con object at 0x046EFCF0>\n\n    def con_read(self):\n        #打开文件\n>       with open('../data_test/send.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data_test/send.yaml'\n\ntestcase\\axtr.py:37: FileNotFoundError"}, "start": 1616492259374, "stop": 1616492259374, "uuid": "3b79c88c-c8f5-4cc9-9a86-b05022940df0", "historyId": "60950418b1ce16e104d0b61868a22992", "testCaseId": "0ff9672df5025b4d5121bf2781139e61", "fullName": "testcase.test_22.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例22"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_22"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "216188-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_22"}]}