{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../testcase/test_dict.yaml'", "trace": "self = <test_07.TestProcurementType object at 0x04339710>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-07' % (self.lab)\n        self.ip = gl.get_value('apiip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.id = self.id = ReadExtract().read_extract()['id']\n\ntestcase\\test_07.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <data_test.axtr.ReadExtract object at 0x04339AD0>\n\n    def read_extract(self):\n        #打开文件\n>       with open('../testcase/test_dict.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../testcase/test_dict.yaml'\n\ndata_test\\axtr.py:7: FileNotFoundError"}, "start": 1616492434445, "stop": 1616492434445, "uuid": "327838e6-fd2c-41a1-af4f-aef441624db3", "historyId": "8b161588a953c64cf26beca11ed8db6b", "testCaseId": "5ae16aab88762868621c31288a32488b", "fullName": "testcase.test_07.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例7"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_07"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "133224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_07"}]}