{"name": "test_newly", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test_dict.yaml'", "trace": "self = <test_04.TestProcurementType object at 0x04EAB050>\n\n    def test_newly(self):\n        self.lab = gl.get_value('lab')\n        self.caseid = '%s-04' % (self.lab)\n        self.ip = gl.get_value('apiip')\n        self.testplanid = gl.get_value('test_plan_id')\n        self.token = gl.get_value('Cookie')\n>       self.id = ReadExtract().read_extract()['id']\n\ntestcase\\test_04.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <axtr.ReadExtract object at 0x04EAB7D0>\n\n    def read_extract(self):\n        #打开文件\n>       with open('test_dict.yaml', encoding='utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'test_dict.yaml'\n\ntestcase\\axtr.py:6: FileNotFoundError"}, "start": 1615860543087, "stop": 1615860543087, "uuid": "43900b00-f52d-40d8-8f59-6124c1370484", "historyId": "09ea47c93403a114b9ba2b3628ea1a44", "testCaseId": "90b6349d51fadaf27b87d0fd9af3eb3b", "fullName": "testcase.test_04.TestProcurementType#test_newly", "labels": [{"name": "feature", "value": "测试用例4"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_04"}, {"name": "subSuite", "value": "TestProcurementType"}, {"name": "host", "value": "DESKTOP-JR3NDOU"}, {"name": "thread", "value": "170332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_04"}]}